apiVersion: v1
kind: Service
metadata:
  name: ums-frontend
  namespace: ums-frontend-ns
spec:
  selector:
    app: ums-frontend
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30005
