service:
  name: ${service_name}
  identifier: ${service_identifier}
  projectIdentifier: ${project_identifier}
  orgIdentifier: ${org_identifier}
  serviceDefinition:
    type: Kubernetes
    spec:
      manifests:
        - manifest:
            identifier: ${service_name}releasemanifest
            type: ReleaseRepo
            spec:
              store:
                type: HarnessCode
                spec:
                  gitFetchType: Branch
                  paths: <+input>
                  branch: main
                  repoName: ${service_manifestreponame}
  gitOpsEnabled: true
