apiVersion: apps/v1
kind: Deployment
metadata:
  name: ums-frontend-deployment
  namespace: ums-frontend-ns
  labels:
    app: ums-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ums-frontend
  template:
    metadata:
      labels:
        app: ums-frontend
    spec:
      containers:
        - name: ums-frontend
          image: docker.io/hvharness/ums-frontend:h7
          imagePullPolicy: Always
          # imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 200m
              memory: 256Mi
          ports:
            - containerPort: 3000
          env:
          - name: APPLICATION_NAME
            valueFrom:
              configMapKeyRef:
                name: ums-frontend-configmap
                key: ums-frontend_APPLICATION_NAME
          - name: UMS_URL
            value: http://localhost:8080
