createNamespace: true
namespace: mydefaultns
name: mybackendservice
replicas: 1
image: /library/my-backend-service:v2.0.0
servicetype: NodePort
serviceport: 8080
containerport: 8080
nodeport: 30055
mydomain: k3s-vm-sandbox.lkvttfwzlki3.instruqt.io
activeprofile: default
env:
  config:
    HARNESS_BUILD: 1
  secrets:
    key2: default
