createNamespace: true
namespace: myprodns
name: mybackendservice
replicas: 1
image: /library/my-backend-service:v2.0.0
servicetype: NodePort
serviceport: 8080
containerport: 8080
nodeport: 30045
mydomain: k3s-vm-sandbox.CHANGEME.instruqt.io
activeprofile: prod
env:
  config:
    HARNESS_BUILD: 1
  secrets:
    key2: value2
